name: project_x
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Bağımlılıklar tekilleştirildi ve doğru hizalandı
  image_picker: ^1.1.2
  firebase_storage: ^12.1.0
  http: ^1.2.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.1
  cloud_firestore: ^5.6.10
  google_generative_ai: ^0.4.3
  google_sign_in: ^6.2.1
  pedometer: ^4.0.1
  shared_preferences: ^2.2.2
  fl_chart: ^0.68.0
  permission_handler: ^11.3.1
  confetti: ^0.8.0
  dotted_border: ^2.1.0
  tuple: ^2.0.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#4CAF50"
  adaptive_icon_foreground: "assets/images/icon.png"